### ISSUE TITLE
ColorCycle: Javascript version

### ISSUE THREAD

**Issue by kana800** [kana800/Side-Projects#43]
The current java-script version of the [color cycle ](https://github.com/kana800/Side-Projects/tree/master/1-Beginner/color_cycle) doesn't work properly.

#### Current Issue
![js](https://user-images.githubusercontent.com/64830745/135703664-31450479-dd03-4b72-a783-e4e51a84915e.gif)

If you check out the above image you can see that *area* around the toggle button doesnt change color with the background.

#### Goal

your goal is to make sure that the *area* around the toggle button changes with the color of the background.

#### Setting Up

1. [Fork the repository and clone it](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
2. Navigate to the correct project folder, its in [`1-Beginner`->`color_cycle`->`js`](https://github.com/kana800/Side-Projects/tree/master/1-Beginner/color_cycle/js)
3. Fix the issue and pull-request.

Let me know if there is any other questions !

Make sure that you get this fix assigned to you before working on it

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this issue?

**Comment by kana800** [comment]
> Can you assign me this issue?

yeah sure ! go ahead
