### ISSUE TITLE
Dollars to Cents: Javascript version

### ISSUE THREAD

**Issue by kana800** [kana800/Side-Projects#44]
**_Make sure that you get this subproject assigned to you before working on it_**

[create a java-script version of dollars to cents](https://github.com/kana800/Side-Projects/tree/master/1-Beginner/dollars_to_cents)

Converting dollars to cents would enable you to practice your fundamental knowledge of programming. Loops, if conditions and a simple algorithm will be used.
Your task is to let the user input a dollar value (float), assuming that it can also accept extra cents (ex. $2.75), and convert it into an integer (in this case, if $2.75 = 275). After this, convert into coins with the sub-type of dollars: penny, nickel, dime and quarter. Use an algorithm that would divide the dollar value to the four coin types, and output few coins as possible.

The challenge: Try this without using any frameworks.

(EX. If you have $0.58, I would have 4 coins: 2 quarters, 0 dimes, 1 nickel and 3 pennies)

## User Stories

-   [x] User can enter a dollar value
-   [x] User can see the total cents from the converted dollar value

## Bonus features

-   [x] User can see how many were pennies, nickels, quarters and dimes from the total cent

## Useful links and resources

-   [Math functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math)
-   [Loops and iterations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration)
-   [Money values in JavaScript](https://timleland.com/money-in-javascript/)

## Example projects

-   [Dollars to cents converter](https://github.com/LimonJuice322/Dollars-to-cents-converter)

**Comment by rahulbhatt1899** [comment]
Hey, I would like to contribute to this issue.

**Comment by abhinaisai2002** [comment]
can I work on this?

**Comment by kana800** [comment]
> Hey, I would like to contribute to this issue.

sure go ahead, the project folder is on `1-Beginner` -> `dollars_to_cents`. create `js` folder and add you files inside the js folder.
if you are adding any images make sure it goes into the `.images` folder.

good luck

**Comment by rahulbhatt1899** [comment]
Alright 👍

**Comment by rahulbhatt1899** [comment]
#46 Added PR please check!
