### ISSUE TITLE
Countdown timer: python version

### ISSUE THREAD

**Issue by kana800** [kana800/Side-Projects#45]
**_Make sure that you get this subproject assigned to you before working on it_**

[create a countdown timer using `PyQt5` or `tkinter`. Listed below are the goals that you need to achieve.](https://github.com/kana800/Side-Projects/blob/master/1-Beginner/countdown_timer)

-   [ ] User can see an event input box containing an event name field, an
date field, an optional time, and a 'Start' button.
-   [ ] User can define the event by entering its name, the date it is
scheduled to take place, and an optional time of the event. If the time is 
omitted it is assumed to be at Midnight on the event date in the local time
zone.
-   [ ] User can see a warning message if the event name is blank.
-   [ ] User can see a warning message if the event date or time are incorrectly
entered. 
-   [ ] User can see a warning message if the time until the event data and time
that has been entered would overflow the precision of the countdown timer.
-   [ ] User can click on the 'Start' button to see the countdown timer start
displaying the days, hours, minutes, and seconds until the event takes place.
-   [ ] User can see the elements in the countdown timer automatically
decrement. For example, when the remaining seconds count reaches 0 the remaining
minutes count will decrement by 1 and the seconds will start to countdown from 59. This progression must take place from seconds all the way up to the remaining days position in countdown display.

**Comment by anirudhgray** [comment]
Hey! I'd love to work on this for hacktoberfest (I'm experienced with Python, but an absolute beginner at contributions). Would be great if you could assign it to me. Let me know if there's anything else I have to keep in mind while working on this :)

**Comment by kana800** [comment]
> Hey! I'd love to work on this for hacktoberfest (I'm experienced with Python, but an absolute beginner at contributions). Would be great if you could assign it to me. Let me know if there's anything else I have to keep in mind while working on this :)

sure go ahead.
the program directory is `1-Beginner`->`countdown_timer`, create a `python` folder here and add your python files here.

Add a README.md file if you want to

**Comment by anirudhgray** [comment]
Hey, I need to ask for clarification on goal5:

> User can see a warning message if the time until the event data and time that has been entered would overflow the precision of the countdown timer.

What do you mean by the "precision of the countdown timer"? @kana800

**Comment by anirudhgray** [comment]
#47: added PR :)
